// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqe3spbwqdy5T3kAF05piP4eZf73F8ZnQ',
    appId: '1:541022722837:web:79bc0925048c3824f7671c',
    messagingSenderId: '541022722837',
    projectId: 'fiscus-e4419',
    authDomain: 'fiscus-e4419.firebaseapp.com',
    storageBucket: 'fiscus-e4419.firebasestorage.app',
    measurementId: 'G-KZS13S7N4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoV02Rtbv2q6keSLWBBRcycwuu69ISOiA',
    appId: '1:541022722837:android:5a1e35488f51f391f7671c',
    messagingSenderId: '541022722837',
    projectId: 'fiscus-e4419',
    storageBucket: 'fiscus-e4419.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC7UM9LWcxXv-vjeQp-vbu1ggEjRSzaNc',
    appId: '1:541022722837:ios:42a79051c40f0a97f7671c',
    messagingSenderId: '541022722837',
    projectId: 'fiscus-e4419',
    storageBucket: 'fiscus-e4419.firebasestorage.app',
    iosBundleId: 'com.example.fiscus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC7UM9LWcxXv-vjeQp-vbu1ggEjRSzaNc',
    appId: '1:541022722837:ios:42a79051c40f0a97f7671c',
    messagingSenderId: '541022722837',
    projectId: 'fiscus-e4419',
    storageBucket: 'fiscus-e4419.firebasestorage.app',
    iosBundleId: 'com.example.fiscus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqe3spbwqdy5T3kAF05piP4eZf73F8ZnQ',
    appId: '1:541022722837:web:89a7e181310de0e8f7671c',
    messagingSenderId: '541022722837',
    projectId: 'fiscus-e4419',
    authDomain: 'fiscus-e4419.firebaseapp.com',
    storageBucket: 'fiscus-e4419.firebasestorage.app',
    measurementId: 'G-NRBV1XXWWJ',
  );
}
